SUCCESS_RETURN_MESSAGE: dict = {"SUCCESS": True}

USER_NOT_FOUND_ERROR = "USER_NOT_FOUND_ERROR"
OBJECT_NOT_FOUND_ERROR = "OBJECT_NOT_FOUND_ERROR"
CHAT_NOT_FOUND_ERROR = "CHAT_NOT_FOUND_ERROR"
MESSAGE_NOT_FOUND_ERROR = "MESSAGE_NOT_FOUND_ERROR"

OBJECT_ALREADY_EXISTS_ERROR = "OBJECT_ALREADY_EXISTS_ERROR"
CHAT_ALREADY_EXISTS_ERROR = "CHAT_ALREADY_EXISTS_ERROR"

UNAUTHORIZED_ERROR = "UNAUTHORIZED_ERROR"
FORBIDDEN_ERROR = "FORBIDDEN_ERROR"
BAD_REQUEST_ERROR = "BAD_REQUEST_ERROR"
CONFLICT_ERROR = "CONFLICT_ERROR"

INCORRECT_LOGIN_ERROR = "INCORRECT_LOGIN_ERROR"
INCORRECT_PASSWORD_ERROR = "INCORRECT_PASSWORD_ERROR"
INVALID_SESSION_ID_ERROR = "INCORRECT_SESSION_ID_ERROR"

LOGIN_ALREADY_TAKEN_ERROR = "LOGIN_ALREADY_TAKEN_ERROR"
USERNAME_ALREADY_TAKEN_ERROR = "USERNAME_ALREADY_TAKEN_ERROR"
EMAIL_ALREADY_TAKEN_ERROR = "EMAIL_ALREADY_TAKEN_ERROR"
PHONE_NUMBER_ALREADY_TAKEN_ERROR = "PHONE_NUMBER_ALREADY_TAKEN_ERROR"

IMAGE_TYPE_NOT_ALLOWED_ERROR = "IMAGE_TYPE_NOT_ALLOWED_ERROR"
IMAGE_SIZE_TOO_LARGE_ERROR = "IMAGE_SIZE_TOO_LARGE_ERROR"