services:
  db:
    image: postgres
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - ./backend/MessengerDBInit.sql:/docker-entrypoint-initdb.d/init.sql
      - postgres_data:/var/lib/postgresql
    ports:
      - ${POSTGRES_PORT}:${POSTGRES_PORT}
    restart: always

  redis:
    image: redis
    container_name: redis
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    command: ["redis-server", "--requirepass", "${REDIS_PASSWORD}"]
    restart: always

  minio:
    image: minio/minio
    container_name: minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    volumes:
      - minio_data:/data
    restart: always

  backend-service:
    build:
      context: .
      dockerfile: DockerfileBackend
    container_name: backend
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_HOST: db
      POSTGRES_PORT: ${POSTGRES_PORT}
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
      MINIO_ENDPOINT: ${MINIO_ENDPOINT}
      REDIS_PASSWORD: ${REDIS_PASSWORD}
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      FRONTEND_URL: ${FRONTEND_URL}
      BACKEND_PORT: ${BACKEND_PORT}
      SMTP_FROM: ${SMTP_FROM}
      SMTP_HOSTNAME: ${SMTP_HOSTNAME}
      SMTP_USERNAME: ${SMTP_USERNAME}
      SMTP_PASSWORD: ${SMTP_PASSWORD}
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    depends_on:
      - db
      - redis
      - minio
    restart: always

  frontend-service:
    build:
      context: .
      dockerfile: DockerfileFrontend
      args:
        VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    container_name: frontend
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      FRONTEND_STATIC_PORT: ${FRONTEND_PORT}
      VITE_API_BASE_URL: ${VITE_API_BASE_URL}
    depends_on:
      - backend-service
    restart: always

volumes:
  postgres_data:
  minio_data: